version: '2'
services:
    touchstone-app:
        image: touchstone
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://touchstone-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=touchstone
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    touchstone-mongodb:
        extends:
            file: mongodb.yml
            service: touchstone-mongodb
